### ISSUE TITLE
Genren lisäluokka biblio_data_elements-tauluun

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/koha-plugin-OKM-stats#11]
### Kehitysehdotukseni

Lisätään genren lisäluokka (084 9_ ‡a) biblio_data_elements-tauluun omaan sarakkeeseen, niin että jokainen ilmentymä erotellaan pilkuilla.

**Comment by emta001** [comment]
Testattu outi- ja vaski-testillä, toimii kuten pitää. Viedään ensi viikon tuotantoon ja tehdään tarvittavat ajot tuotantoihin.

Tehtävät ajot:

- [ ] Siili
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Vaara
- [ ] Lappi
- [ ] OUTI
- [ ] Vaski

**Comment by emta001** [comment]
Ajot tehty ja sarakkeet täytetty. Suljen tiketin.
