### ISSUE TITLE
Raportointityökalu ja OKM-tilastosta puuttuvat arvot Aktiiviset asiakkaat -sarakkeesta

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/koha-plugin-OKM-stats#15]
### Mikä vikana?

Helle-Kohan Raportointityökalun OKM-tilastoista puuttuu arvot Aktiiviset asiakkaat -sarakkeesta koskien tilastoja:
Toukokuu 2024 
Kesäkuu 2024

**Comment by emta001** [comment]
Kaikille kimpoille on nyt ajettu uusiksi toukokuun ja kesäkuun tilastot.

**Comment by MikkoLiimatainen** [comment]
Vaskin tilastot näyttävät olevan kunnossa.

**Comment by pirliis** [comment]
Samoin OUTIn tilastot.

**Comment by Kati-Helle** [comment]
Hellenkin.
