### ISSUE TITLE
Daisy-lainaajien määrä mukaan OKM-raportille

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/koha-plugin-OKM-stats#2]
### Kehitysehdotukseni

OKM:lle raportoidaan myös Celia-asiakkaiden määrä (määräksi lasketaan Daisy-äänikirjoja lainanneiden asiakkaiden määrä kirjastojärjestelmässä + Celia-palveluun rekisteröityjen asiakkaiden määrä). Järjestelmästä lainanneiden asiakkaiden määrä on aiemmin laskettu sql-[raportilla](https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Valmiita_SQL-raportteja#Celia-lainaajien-m%C3%A4%C3%A4r%C3%A4-vuoden-ja-kunnan-mukaan), mutta mahtaisiko sama luku olla helposti lisättävissä tilastotyökaluun yhdeksi sarakkeeksi jolloin erillistä raporttia ei tarvittaisi?

Mikko on Vaskin tallennettuihin raportteihin päivittänyt Redminen raportista uuden version (vanhassa versiossa rajaus itemtypeen, jota ei enää ole käytössä), jonka varmaan voisi joka tapauksessa päivittää valmiisiin sql-raportteihin vanhan raportin tilalle, jos uutta saraketta ei päädytä ottamaan mukaan okm-raportille?

```
select count(distinct(borrowernumber)) as Lainaajat
from statistics s
left join items i ON i.itemnumber=s.itemnumber
left join koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde ON bde.biblioitemnumber=i.biblionumber
where type in ('issue') 
and branch like <<Kirjoita kirjastolyhenteen alku ja %>> 
and year(datetime)=<<Vuosiluku>>
and usercode not in ('EITILASTO')
and bde.celia=1
```

### Jotain muuta?

Siirretty GitHubiin Redminen tiketistä https://tiketti.koha-suomi.fi/issues/5585

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmän päätös 16.1.2023: Lisätään toiminnallisuus OKM-raportointiin vuoden 2022 tilastojen oton jälkeen.

**Comment by emta001** [comment]
Viety testeille. Tällä hetkellä siellä ei ole muuta kuin tyhjä "Celia-lainaajat"-sarake, mutta voin käydä ajamassa uusia tilastoja niin pääsette testaamaan tätä.

**Comment by sksandel** [comment]
Oliko tarkoitus, että pyydellään tilastoajot? Vaskin testeillä näkyy "Celia-lainaajat" -sarake. Voisin katsoa vielä luvutkin, jos saadaan joku tilasto testattavaksi.

**Comment by emta001** [comment]
> Oliko tarkoitus, että pyydellään tilastoajot? Vaskin testeillä näkyy "Celia-lainaajat" -sarake. Voisin katsoa vielä luvutkin, jos saadaan joku tilasto testattavaksi.

Oli, mutta näemmä edellisessä kommentissa se ajatus hukkui. Voin käydä kohta ajamassa sinne tilastoa.

**Comment by emta001** [comment]
Tässä tuli pieni mutka matkaan, vaski-testin bde-taulu on tyhjä. Pitää ajaa se ensin ensi yönä, ennenkuin saadaan tilastoja ulos.

**Comment by emta001** [comment]
Bde-taulu on nyt kunnossa, mutta lainoja ei jostain syystä tullut raportille (id 16). Yritän saada ne vielä pelittämään.

**Comment by emta001** [comment]
Okei eli ongelmana on se, että vaski-testin statistics-taulussa ei ole categorycodea oikeastaan millään rivillä. Ne pitäisi ensi täyttää. Mulla on siihen ajo, mutta se on aika raskas, niin pitänee katella illemmalla uudestaan.

**Comment by emta001** [comment]
Noniin, pienen säätämisen jälkeen Vaskin testillä on nyt raportti 17, jossa on OKM-tilastot ajalle 1.5.2022-31.5.2022. Ainakin sinne näkyisi tulleen Celia-lainaajia.

**Comment by ajrajala** [comment]
Hmm, en onnistu saamaan raportointityökalun raporttilistaukseen näkyville yhtään raporttia, ctrl + f5 ei auta. Mistäköhän voisi kiikastaa? 🤔 
![kuva](https://github.com/KohaSuomi/koha-plugin-OKM-stats/assets/44638512/e0bc8f36-1b63-4e7b-8024-b082f49dcaa6)

**Comment by pknuuti** [comment]
Onko tämä käytettävissä vain Vaskin testillä? Vaaran testill näyttää vain nollaa nämä Celia-sarakkeet.

**Comment by emta001** [comment]
> > Onko tämä käytettävissä vain Vaskin testillä? Vaaran testillä näyttää vain nollaa nämä Celia-sarakkeet.
> 
> Joo on, voin toki vilasta saako nämä vaaraankin ilman hirveää säätöä.

Onnistui, siellä on nyt rapsa 94, jossa on mukana Celia-lainaajat.

**Comment by ajrajala** [comment]
Vertailin okm-raportin lukuja ajamalla testillä [raporttikirjaston sql-kyselyn](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#celia-lainaajien-m%C3%A4%C3%A4r%C3%A4-vuoden-ja-kunnan-mukaan) sillä muokkauksella, että datetime oli rajattu toukokuulle 2022. Esim. RA_OKM luku on okm-tilastossa 16, mutta sql-kyselyllä tulee 11. Samaten TU_OKM luku okm-tilastossa on 14 ja sql-kyselyllä 10.

Onko eroihin luvuissa jokin luonnollinen selitys? En oikein keksinyt millä muulla tavoin olisi noiden okm-raportille tulleiden lukujen oikeellisuutta tarkastellut.

**Comment by pknuuti** [comment]
Vaarassa on samansuuntaista virhettä luvuissa. JOE_OKM antaa Celia-lainaajien määräksi 70, koko vuoden 2022 sq-lraportti luvun 54. LIE_OKM virhe on pienempi (15 vs. 14), NUR_OKM vastaavat luvut 5 vs. 3. 
Joku tässä ei nyt täsmää.

**Comment by emta001** [comment]
Ainakin tuossa raporttikirjaston rapsassa on käytetty vain issue-arvoa, OKM:n laskee myös renew-arvoiset lainoiksi. Eli tuota pitäisi korjata. Vai onko se tarkoituksella noin?

**Comment by emta001** [comment]
> Lueskelin tuota tilasto-ohjetta ja sen mukaan "Lainaajiksi lasketaan tilastointivuonna lainausoikeuttaan käyttäneet", eli kyllä vuositasolla jos asiakas uusii Daisy-lainansa 2022 tammikuussa eikä hänellä ole sinä vuonna lainkaan Daisy-ensilainoja, niin hänet on laskettava 2022 lainaajatilastoon mukaan.
> 
Näinhän se on.

> Selittäisikö tuo issue vs issue+renew näin suuret erot luvuissa?
Testasin vaski-testillä lisäämällä sql-raporttiin myös renew-arvon ja sain tulokseksi 16. Eli kyllä se selittää.

**Comment by sksandel** [comment]
Sitten tämä on taputeltu? Suljetaanko tiketti vasta kun on viety tuotantoon?

**Comment by emta001** [comment]
Juu, suljetaan vasta kun on viety tuotantoon.
