### ISSUE TITLE
Varoitus "substr outside of string" update_biblio_data_elements.pl ajossa  

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-OKM-stats#3]
### Mikä vikana?

Joidenkin tietueiden kohdalla update_biblio_data_elements.pl antaa varoituksen "substr outside of string on BiblioDataelement.pm line 100". Ilmeisesti kun tutkitaan tietueen kieltä, 008-kenttä on lyhyempi kuin 35 merkkiä (tuosta alkaen pitäisi periaattessa löytyä kielikoodi). 

### Mitä pitäisi tapahtua

Varoitusta ei pitäisi syntyä.

**Comment by AnneliO** [comment]
008-kenttä pitäisi aina olla 40 merkkiä pitkä, olisiko luettelointivirhe?

**Comment by emta001** [comment]
> 008-kenttä pitäisi aina olla 40 merkkiä pitkä, olisiko luettelointivirhe?

Todennäköisesti kyllä, eli eipä tehdä tälle mitään plugarin päässä. Suljen tiketin.
