### ISSUE TITLE
Aikuisten ja lasten kauno/tietokirjat tilastoituvat väärin

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-OKM-stats#5]
### Mikä vikana?

Varkaudessa huomattiin heittoa aikuisten ja lasten kauno/tietokirjojen hankinnoissa, luvut ovat liian pieniä. Tämä johtuu siitä, että tällä hetkellä raportointiplugin ottaa niteiden luokan items.cn_sort-sarakkeesta, jonka alussa voi olla esim. PKA kuten Varkauden aineistossa. 

Korjataan ottamalla niteen kauno/tieto tieto biblio_data_elements-taulun fiction-sarakkeesta. Siihen kerätään data MARC kentän 84$a ensimmäisestä ilmentymästä, jossa noita aakkosalkuja ei ole (oletettavasti).

**Comment by emta001** [comment]
AVIn ohjeistuksen mukaisesti jaon tulee perustua niteen luokkaan, ei tietueen. Muutetaan toiminnallisuutta niin, että cn_sort-sarakkeen alussa olevat kirjaimet jätetään huomiotta.

**Comment by AnneliO** [comment]
Sovittu 19.1.2023 Varkauden ja Lumpeiden pääkäyttäjän Helin kanssa, että korjataan Varkauden niteiden cn_sort- ja itemcallnumber-kentät samaan muotoon kuin muilla kimpan kirjastoilla, jolloin tilastot muodostuvat oikein. Koodimuutos ei käytännössä ole mahdollinen, koska pääsana voi sisältää numeroita, jolloin niihin saatetaan tarttua virheellisesti luokkatiedon sijaan.

Teen erillisen tiketin korjausajoista ja suljen tämän tiketin.
