### ISSUE TITLE
Aineiston julkaisuvuosi mukaan bde-tauluun

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-OKM-stats#8]
Saraketta voidaan käyttää mm. PowerBi-raporteissa sen sijaan, että tieto haetaan suoraan metadatasta.

**Comment by emta001** [comment]
Viety testeille ja toiminee oikein. Tuodaan tämä seuraavassa päivityksessä tuotantoon. Käyttöönotto vaatii install_plugins.pl-skriptin ajamisen, tämä päivittää sarakkeen automaattisesti.

**Comment by AnneliO** [comment]
En nyt ole varma (en löytänyt tähän liittyvää keskustelua), miksi tämä lisäys on tehty, mutta julkaisuvuosi löytyy myös biblioitems.publicatioyear-sarakkeesta. Eli tietoa ei käsittääkseni tarvitse nytkään hakea metadatasta. :)

**Comment by Tuomas-Kyyti** [comment]
Se ero noissa näyttää olevan, että metadatasta ja tästä uudesta bde:stä löytyy samat vuodet, mutta biblioitems.publicationyear-kentästä löytyy vähän vähemmän vuosilukuja. Vaikuttaisi kuin sinne vuodet menevät 260c-kentästä ja bde:hen metadatasta. Ainakin meillä biblioitemistä puuttuu paljon muutaman viime vuoden aikakauslehtien vuosia ja ne näköjään puuttuvat myös 260c-kentästä.

**Comment by AnneliO** [comment]
biblioitems.publicationyear-kenttään pitäisi mennä tietueista sekä 260c että 264c -kenttien tiedot. Päätimme yhteiset Kohan MARC-määritykset viime vuonna [pääkäyttäjien viikon 14 palaverissa](https://koha-suomi.fi/paakayttajat2022#viikko-14-muistio). Onkohan nyt käynyt niin, että Kyytissä ei ole ajettu misc/batchRebuildBiblioTables.pl -ajoa määritysten muuttamisen jälkeen?

**Comment by AnneliO** [comment]
Löyhästi tähän liittyen, olen joskus lisännyt OUTIin yhteisön raporttikirjastosta tällaisen kyselyn, joka etsii tietueet, joissa metadatasta 008 ja biblioitems.publicationyear eivät vastaa toisiaan:

```
SELECT CONCAT('<a target="new" href=\"/cgi-bin/koha/catalogue/detail.pl?biblionumber=',biblio.biblionumber,'\">',biblio.title,'</a>') AS Title, biblioitems.publicationyear, control008.008pubdate 
FROM (SELECT biblionumber, SUBSTR(ExtractValue(biblio_metadata.metadata,'//controlfield[@tag="008"]'),8,4)  AS 008pubdate FROM biblio_metadata) AS control008 
JOIN biblio USING(biblionumber)
JOIN biblioitems USING(biblionumber)
JOIN biblio_metadata USING(biblionumber)
WHERE biblioitems.publicationyear != control008.008pubdate 
AND control008.008pubdate != ''
```

OUTIssa näitä on lähemmäs 54 000 tietuetta, mutta ne ovat enimmäkseen vanhoja tietueita (ennen MARC21:stä ja RDA:ta tehtyjä), mutta on mukana uudempaakin aineistoa. En tunne niin hyvin kuvailusääntöjä, että osaisin sanoa, miksi uudemmassakin aineistossa noissa on eroja.

**Comment by Tuomas-Kyyti** [comment]
> Jäin myös miettimään, että mistä kohtaa "metadataa" tieto haetaan? 260/264 ovat myös osa metadataa, mutta haetaanko vuosiluku esim. 008:sta metadatasta?

Itse ymmärsin tämän metadata-sanan tässä yhteydessä tarkoittavan nimen omaan 008-kenttää. PowerBI-raporteissa olen hakenut näin SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="008"]'),8,4), mutta vaihdoin niihin nyt bde:n.

**Comment by Tuomas-Kyyti** [comment]
> biblioitems.publicationyear-kenttään pitäisi mennä tietueista sekä 260c että 264c -kenttien tiedot. Päätimme yhteiset Kohan MARC-määritykset viime vuonna [pääkäyttäjien viikon 14 palaverissa](https://koha-suomi.fi/paakayttajat2022#viikko-14-muistio). Onkohan nyt käynyt niin, että Kyytissä ei ole ajettu misc/batchRebuildBiblioTables.pl -ajoa määritysten muuttamisen jälkeen?

Meillä uusissa aikakauslehdissä ei ole vuotta 260c- eikä 264c-kentissä. Ilmeinen toistuva kuvailuvirhe. 008-kentässä se on ja siksi raportti on toiminut paremmin kun hakee 008-kentästä tai nyt bde:stä.

**Comment by AnneliO** [comment]
> > Jäin myös miettimään, että mistä kohtaa "metadataa" tieto haetaan? 260/264 ovat myös osa metadataa, mutta haetaanko vuosiluku esim. 008:sta metadatasta?
> 
> Itse ymmärsin tämän metadata-sanan tässä yhteydessä tarkoittavan nimen omaan 008-kenttää. PowerBI-raporteissa olen hakenut näin SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="008"]'),8,4), mutta vaihdoin niihin nyt bde:n.

Niin justiinsa. Tuolla samalla "tekniikalla" voi hakea myös 260/264c-kentistä, niin siksi en ole varma, mihin metadatalla viitataan. :)

Esim.

```
SELECT title, ExtractValue(bm.metadata, '//datafield[@tag="264"]/subfield[@code="c"]')
FROM biblio_metadata bm
```

**Comment by emta001** [comment]
Ajatuksena oli siis keventää näitä PowerBi-raportteja, joissa aiemmin käytettiin tuota ExtractValueta. Tuon biblioitems.publicationyearin käyttäminen ei näitä myöskään kevennä, koska silloin on tehtävä liitos myös deletedbiblioitemsiin (joka kyllä pitänee tehdä joka tapauksessa jonkin muun datan kohdalla, mutta yritetään nyt taklata tätä liitos ongelmaa nyt ainakin tämän julkaisuvuoden kannalta :D).  Ja tieto poimitaan tosiaan kentästä 008.
